spring:
  application:
    name: reader-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8280

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



