spring:
  application:
    name: issuance-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver

server:
  port: 8380

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

timer:
  enabled: true